[package]
name = "e41-50"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3.0"
itertools = "0.9.0"
timings_proc_macro = {path = "../timings-proc-macro"}
num="0.4.0"
