[package]
name = "e21-30"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
num-bigint = "0.4.2"
bigdecimal = "0.3.0"
timings_proc_macro = {path = "../timings-proc-macro"}
