[package]
name = "e1-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timings_proc_macro = {path = "../timings-proc-macro"}
